version = 0.1

[default.deploy.parameters]
stack_name = "band-scheduler-backend"
resolve_s3 = true
s3_prefix = "band-scheduler-backend"
region = "ap-northeast-1"
profile = "AdministratorAccess-490224159917"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
